#45 iso.Key.nearest_note - upper bound issue - fix to amended test
ideoforms/isobar pull request #46
Opened 2023-05-01 21:29 UTC by piotereks

2024-01-02 11:50 UTC, ideoforms requested changes
Thanks for this patch and sorry for the slow reply! I've only had limited bandwidth to deal with PRs over the past few months. One change then good to go.

2024-01-02 11:50 UTC, ideoforms commented on isobar/key.py
> +                    if dist == abs(abs(semi-pitch)-12):
Hardcoded `12` here should be `self.scale.octave_size`, then good to merge!

2024-01-03 20:57 UTC, ideoforms approved these changes

2024-01-03 20:57 UTC, merged

2024-01-03 21:00 UTC, ideoforms commented
@piotereks Unit test now seems to be failing 🤔

2024-01-03 22:08 UTC, piotereks commented
Fixed with other commit. Nearest note was faulty because of 2 additional
things:
- non deterministic selection of note in case lowe and upper note have same
distance
- nearest note was disregarding other than 0 tonic for scale

Pozdrawiam
Piotr

śr., 3 sty 2024, 22:01 użytkownik Daniel Jones ***@***.***>
napisał:

> @piotereks <https://github.com/piotereks> Unit test now seems to be
> failing 🤔
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ideoforms/isobar/pull/46#issuecomment-1875966085>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQTBLDFTUB6XZ7VMN6HBIJTYMXBI5AVCNFSM6AAAAAAXSGU3POVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZVHE3DMMBYGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>